### ISSUE TITLE
0.2.0 version removes eslint from node_modules/.bin/ folder

### ISSUE THREAD

**Issue by k03mad** [xg-wang/pruner-cli#2]
Hello,

Last version removes eslint bin from node_modules.
So locally installed eslint not working after prune...

**Comment by xg-wang** [comment]
Hi, I removed [`eslint`](https://github.com/xg-wang/pruner-cli/commit/3f3717c6d6bb5fe958f05e272a1b52ecb5d68946#diff-04c6e90faac2675aa89e2176d2eec7d8L57`) from default, it should work now.
BTW I think we might need a white list to protect folders like `.bin`.
